config/routes.rb
SoundingBoard::Application.routes.draw do
  resources :users
  resources :posts do
    collection do
      get 'search'
      get 'refresh'
    end

    resources :comments, :only => [:create]
  end


  resources :comments, :except => [:create]

  get '/login'   => 'users#login'
  post '/login'  => 'users#create_login'
  post '/logout' => 'users#logout'

  get '/my_posts' => 'my_posts#index'

  get '/posts/new' => 'posts#create' # HUH? WHAT IS THIS?

  post '/comments/:id/upvote' => "comments#upvote"
  post '/comments/:id/downvote' => "comments#downvote"

  get '/songs/search' => "songs#search"
  get '/songs/search_for_use_by_comment' => "songs#search_for_use_by_comment"
  get '/songs/display_search_results' => "songs#display_search_results"

  root to: "application#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :short_url, :title, :artist, :album, :year
  has_many :posts
  has_many :comments
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def search
    # puts "HELLO"
    # p params[:post]
    @post_data = params[:post]
    # puts "POST DATA!!!"
    # p params
    # puts "END POST DATA!!!"
    @songs = []
    @res = rdio_search(params[:post][:song])[0..29]
    # puts res
    @res.each do |track|
      @song = Song.new(
        :short_url => track["embedUrl"],
        :title => track["name"],
        :artist => track["artist"],
        :album => track["album"],
        :year => 0
        )
      @songs << @song
    end

    render "rdio_search_results", :locals => { :post_data => params[:post] }
  end

  def search_for_use_by_comment
    # puts "HELLO"
    # p params[:post]
    @comment_data = params[:comment]

    # puts "COMMENT DATA!!!"
    # p params
    # puts "END COMMENT DATA!!!"

    # @post_id = params[:post_id]
    @songs = []
    #HERE
    @res = rdio_search(params[:comment][:song])[0..29]
    # puts res
    @res.each do |track|
      @song = Song.new(
        :short_url => track["embedUrl"],
        :title => track["name"],
        :artist => track["artist"],
        :album => track["album"],
        :year => 0
        )
      @songs << @song
    end

    # if @songs.empty?

    # else
      render "rdio_search_results_for_comments", :locals => { :comment_data => params[:comment], :post_id => params[:post_id] }
    # end
  end
end

app/views/songs/rdio_search_results.html.erb
<div class="rdio_search_results">
  <h3>Search Results</h3>
  <% if @songs.empty? %>
    <h4>No songs were found that matched your search criteria. Try a different search term.</h4>
  <% else %>
    <% @songs.each do |song| %>
        <%= form_for :post, :url => posts_path, :method => "post" do |f| %>
        <input type="hidden" value="<%= post_data[:title] %>" name="post_title">
        <input type="hidden" value="<%= post_data[:motivation] %>" name="post_motivation">
        <input type="hidden" value="<%= song[:title] %>" name="song_title">
        <input type="hidden" value="<%= song[:short_url] %>" name="song_embed_url">
        <input type="hidden" value="<%= song[:artist] %>" name="song_artist">
        <input type="hidden" value="<%= song[:album] %>" name="song_album">

        <%= f.submit  "#{song.artist} - #{song.album} - #{song.title}" %>
        <% end %>
    <% end %>
  <% end %>


</div>

app/views/songs/rdio_search_results_for_comments.html.erb
<div class="rdio_search_results">
  <h3>Search Results</h3>

  <% if @songs.empty? %>
    <h4>No songs were found that matched your search criteria. Create
      comment anyway?</h4>
    <%= form_for :comment, :url => "/posts/#{post_id}/comments", :action => "create", :method => "post" do |f| %>
        <input type="hidden" value="<%= comment_data[:body] %>" name="comment_body">
        <input type="hidden" value="<%= post_id %>" name="post_id">

        <%= f.submit "Create Comment" %>
    <% end %>
  <% else %>
    <% @songs.each do |song| %>
      <%= form_for :comment, :url => "/posts/#{post_id}/comments", :action => "create", :method => "post" do |f| %>
        <input type="hidden" value="<%= comment_data[:body] %>" name="comment_body">
        <input type="hidden" value="<%= song[:title] %>" name="song_title">
        <input type="hidden" value="<%= song[:short_url] %>" name="song_embed_url">
        <input type="hidden" value="<%= song[:artist] %>" name="song_artist">
        <input type="hidden" value="<%= song[:album] %>" name="song_album">
        <input type="hidden" value="<%= post_id %>" name="post_id">

        <%= f.submit  "#{song.artist} - #{song.album} - #{song.title}" %>
      <% end %>
    <% end %>
  <% end %>


</div>