config/routes.rb
SoundingBoard::Application.routes.draw do
  resources :users
  resources :posts do
    collection do
      get 'search'
      get 'refresh'
    end

    resources :comments, :only => [:create]
  end


  resources :comments, :except => [:create]

  get '/login'   => 'users#login'
  post '/login'  => 'users#create_login'
  post '/logout' => 'users#logout'

  get '/my_posts' => 'my_posts#index'

  get '/posts/new' => 'posts#create' # HUH? WHAT IS THIS?

  post '/comments/:id/upvote' => "comments#upvote"
  post '/comments/:id/downvote' => "comments#downvote"

  get '/songs/search' => "songs#search"
  get '/songs/search_for_use_by_comment' => "songs#search_for_use_by_comment"
  get '/songs/display_search_results' => "songs#display_search_results"

  root to: "application#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundingBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "nav_bar">


    <% if session[:current_user_id] != nil %>
      <li><a class='align-center title' href='/'>Sounding Board</a></li>
      <%= form_for :user, :url => { :action => "logout", :controller => "users" } do |f| %>
      <li><a><%= f.submit "Logout", :id=> "logout" %></a></li>
      <li><a class='align-right nav-link' <%= link_to("Create Post", posts_new_path) %> ></a></li>
      <li><a class='align-right nav-link' <%= link_to("My Post", my_posts_path) %> ></a></li>
      <% end %>
    <% else %>
    <li><a class='align-center title' href='/'>Sounding Board</a></li>
      <li><a class='align-right nav-link' <%= link_to("Login", login_path) %> ></a></li>
     <li><a class='align-right nav-link'<%= link_to("Sign Up", new_user_path) %> ></a></li>
    <% end %>
  </div>

<%= yield %>


</body>

<div id="footer">
  <section>© 2013 All Rights Reserved - TeamDelta.com</section>
</div>
</html>